### ISSUE TITLE
ember-cli-update failing with error related to `rev-parse null`

### ISSUE THREAD

**Issue by barelyknown** [ember-cli/ember-cli-update#699] opened 2019-09-11 17:16 UTC
I'm not able to update to a new version with `ember update`. See below:

```
$ DEBUG=ember-cli-update,boilerplate-update,git-diff-apply ember update
  git-diff-apply npm view ember-cli versions --json +0ms
  git-diff-apply [
  git-diff-apply   "0.0.0",
  git-diff-apply   "0.0.1",
  git-diff-apply   "0.0.2",
  git-diff-apply   "0.0.3",
  git-diff-apply   "0.0.4",
  git-diff-apply   "0.0.5",
  git-diff-apply   "0.0.6",
  git-diff-apply   "0.0.7",
  git-diff-apply   "0.0.8",
  git-diff-apply   "0.0.9",
  git-diff-apply   "0.0.10",
  git-diff-apply   "0.0.11",
  git-diff-apply   "0.0.12",
  git-diff-apply   "0.0.13",
  git-diff-apply   "0.0.14",
  git-diff-apply   "0.0.15",
  git-diff-apply   "0.0.16",
  git-diff-apply   "0.0.18",
  git-diff-apply   "0.0.19",
  git-diff-apply   "0.0.20",
  git-diff-apply   "0.0.21",
  git-diff-apply   "0.0.22",
  git-diff-apply   "0.0.23",
  git-diff-apply   "0.0.24",
  git-diff-apply   "0.0.25",
  git-diff-apply   "0.0.27",
  git-diff-apply   "0.0.28",
  git-diff-apply   "0.0.29",
  git-diff-apply   "0.0.32",
  git-diff-apply   "0.0.33",
  git-diff-apply   "0.0.34",
  git-diff-apply   "0.0.35",
  git-diff-apply   "0.0.36",
  git-diff-apply   "0.0.37",
  git-diff-apply   "0.0.38",
  git-diff-apply   "0.0.39",
  git-diff-apply   "0.0.40",
  git-diff-apply   "0.0.41",
  git-diff-apply   "0.0.42",
  git-diff-apply   "0.0.43",
  git-diff-apply   "0.0.44",
  git-diff-apply   "0.0.45",
  git-diff-apply   "0.0.46",
  git-diff-apply   "0.0.47",
  git-diff-apply   "0.1.0",
  git-diff-apply   "0.1.1",
  git-diff-apply   "0.1.2",
  git-diff-apply   "0.1.3",
  git-diff-apply   "0.1.4",
  git-diff-apply   "0.1.5",
  git-diff-apply   "0.1.6",
  git-diff-apply   "0.1.7",
  git-diff-apply   "0.1.8",
  git-diff-apply   "0.1.9",
  git-diff-apply   "0.1.10",
  git-diff-apply   "0.1.11",
  git-diff-apply   "0.1.12",
  git-diff-apply   "0.1.13",
  git-diff-apply   "0.1.14",
  git-diff-apply   "0.1.15",
  git-diff-apply   "0.2.0-beta.1",
  git-diff-apply   "0.2.0",
  git-diff-apply   "0.2.1",
  git-diff-apply   "0.2.2",
  git-diff-apply   "0.2.3",
  git-diff-apply   "0.2.4",
  git-diff-apply   "0.2.5",
  git-diff-apply   "0.2.6",
  git-diff-apply   "0.2.7",
  git-diff-apply   "1.13.0",
  git-diff-apply   "1.13.1",
  git-diff-apply   "1.13.5",
  git-diff-apply   "1.13.6",
  git-diff-apply   "1.13.7",
  git-diff-apply   "1.13.8",
  git-diff-apply   "1.13.9",
  git-diff-apply   "1.13.10",
  git-diff-apply   "1.13.11",
  git-diff-apply   "1.13.12",
  git-diff-apply   "1.13.13",
  git-diff-apply   "1.13.14",
  git-diff-apply   "1.13.15",
  git-diff-apply   "2.2.0-beta.1",
  git-diff-apply   "2.2.0-beta.2",
  git-diff-apply   "2.2.0-beta.3",
  git-diff-apply   "2.2.0-beta.4",
  git-diff-apply   "2.2.0-beta.5",
  git-diff-apply   "2.2.0-beta.6",
  git-diff-apply   "2.3.0-beta.1",
  git-diff-apply   "2.3.0-beta.2",
  git-diff-apply   "2.3.0",
  git-diff-apply   "2.4.0",
  git-diff-apply   "2.4.1",
  git-diff-apply   "2.4.2",
  git-diff-apply   "2.4.3",
  git-diff-apply   "2.5.0",
  git-diff-apply   "2.5.1",
  git-diff-apply   "2.6.0-beta.1",
  git-diff-apply   "2.6.0-beta.2",
  git-diff-apply   "2.6.0-beta.3",
  git-diff-apply   "2.6.0",
  git-diff-apply   "2.6.1",
  git-diff-apply   "2.6.2",
  git-diff-apply   "2.6.3",
  git-diff-apply   "2.7.0-beta.1",
  git-diff-apply   "2.7.0-beta.2",
  git-diff-apply   "2.7.0-beta.3",
  git-diff-apply   "2.7.0-beta.4",
  git-diff-apply   "2.7.0-beta.5",
  git-diff-apply   "2.7.0-beta.6",
  git-diff-apply   "2.7.0",
  git-diff-apply   "2.8.0-beta.1",
  git-diff-apply   "2.8.0-beta.2",
  git-diff-apply   "2.8.0-beta.3",
  git-diff-apply   "2.8.0",
  git-diff-apply   "2.9.0-beta.1",
  git-diff-apply   "2.9.0-beta.2",
  git-diff-apply   "2.9.0",
  git-diff-apply   "2.9.1",
  git-diff-apply   "2.10.0-beta.1",
  git-diff-apply   "2.10.0-beta.2",
  git-diff-apply   "2.10.0",
  git-diff-apply   "2.10.1",
  git-diff-apply   "2.11.0-beta.1",
  git-diff-apply   "2.11.0-beta.2",
  git-diff-apply   "2.11.0",
  git-diff-apply   "2.11.1",
  git-diff-apply   "2.12.0-beta.1",
  git-diff-apply   "2.12.0-beta.2",
  git-diff-apply   "2.12.0",
  git-diff-apply   "2.12.1",
  git-diff-apply   "2.12.2",
  git-diff-apply   "2.12.3",
  git-diff-apply   "2.13.0-beta.1",
  git-diff-apply   "2.13.0-beta.2",
  git-diff-apply   "2.13.0-beta.3",
  git-diff-apply   "2.13.0-beta.4",
  git-diff-apply   "2.13.0",
  git-diff-apply   "2.13.1",
  git-diff-apply   "2.13.2",
  git-diff-apply   "2.13.3",
  git-diff-apply   "2.14.0-beta.1",
  git-diff-apply   "2.14.0-beta.2",
  git-diff-apply   "2.14.0",
  git-diff-apply   "2.14.1",
  git-diff-apply   "2.14.2",
  git-diff-apply   "2.15.0-beta.1",
  git-diff-apply   "2.15.0-beta.2",
  git-diff-apply   "2.15.0",
  git-diff-apply   "2.15.1",
  git-diff-apply   "2.16.0-beta.1",
  git-diff-apply   "2.16.0-beta.2",
  git-diff-apply   "2.16.0",
  git-diff-apply   "2.16.1",
  git-diff-apply   "2.16.2",
  git-diff-apply   "2.17.0-beta.1",
  git-diff-apply   "2.17.0-beta.2",
  git-diff-apply   "2.17.0",
  git-diff-apply   "2.17.1",
  git-diff-apply   "2.17.2",
  git-diff-apply   "2.18.0-beta.1",
  git-diff-apply   "2.18.0-beta.2",
  git-diff-apply   "2.18.0",
  git-diff-apply   "2.18.1",
  git-diff-apply   "2.18.2",
  git-diff-apply   "3.0.0-beta.1",
  git-diff-apply   "3.0.0-beta.2",
  git-diff-apply   "3.0.0",
  git-diff-apply   "3.0.1",
  git-diff-apply   "3.0.2",
  git-diff-apply   "3.0.3",
  git-diff-apply   "3.0.4",
  git-diff-apply   "3.1.0-beta.1",
  git-diff-apply   "3.1.0",
  git-diff-apply   "3.1.1",
  git-diff-apply   "3.1.2",
  git-diff-apply   "3.1.3",
  git-diff-apply   "3.1.4",
  git-diff-apply   "3.2.0-beta.1",
  git-diff-apply   "3.2.0-beta.2",
  git-diff-apply   "3.2.0",
  git-diff-apply   "3.3.0",
  git-diff-apply   "3.4.0-beta.1",
  git-diff-apply   "3.4.0-beta.2",
  git-diff-apply   "3.4.0-beta.3",
  git-diff-apply   "3.4.1",
  git-diff-apply   "3.4.2-beta.1",
  git-diff-apply   "3.4.2",
  git-diff-apply   "3.4.3",
  git-diff-apply   "3.4.4",
  git-diff-apply   "3.5.0-beta.1",
  git-diff-apply   "3.5.0-beta.2",
  git-diff-apply   "3.5.0",
  git-diff-apply   "3.5.1",
  git-diff-apply   "3.6.0-beta.1",
  git-diff-apply   "3.6.0",
  git-diff-apply   "3.6.1",
  git-diff-apply   "3.7.0-beta.1",
  git-diff-apply   "3.7.0-beta.2",
  git-diff-apply   "3.7.0",
  git-diff-apply   "3.7.1",
  git-diff-apply   "3.8.0-beta.1",
  git-diff-apply   "3.8.0",
  git-diff-apply   "3.8.1",
  git-diff-apply   "3.8.2",
  git-diff-apply   "3.8.3",
  git-diff-apply   "3.9.0-beta.1",
  git-diff-apply   "3.9.0-beta.2",
  git-diff-apply   "3.9.0",
  git-diff-apply   "3.10.0-beta.1",
  git-diff-apply   "3.10.0-beta.2",
  git-diff-apply   "3.10.0",
  git-diff-apply   "3.10.1",
  git-diff-apply   "3.11.0-beta.1",
  git-diff-apply   "3.11.0-beta.3",
  git-diff-apply   "3.11.0",
  git-diff-apply   "3.12.0",
  git-diff-apply   "3.13.0-beta.1"
  git-diff-apply ]
  git-diff-apply  +596ms
  git-diff-apply git status --porcelain +5ms
  git-diff-apply git clone --mirror https://github.com/ember-cli/ember-new-output /var/folders/2_/zcg8_9w57xd9nn50s04y1rcc0000gn/T/tmp-91690zG8YVrakEoBc/.git +35ms
  git-diff-apply  +484ms
  git-diff-apply git --git-dir="/var/folders/2_/zcg8_9w57xd9nn50s04y1rcc0000gn/T/tmp-91690zG8YVrakEoBc/.git" rev-parse vnull +0ms
Command failed: git --git-dir="/var/folders/2_/zcg8_9w57xd9nn50s04y1rcc0000gn/T/tmp-91690zG8YVrakEoBc/.git" rev-parse vnull
fatal: ambiguous argument 'vnull': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by kellyselden** [comment] 2019-09-11 20:53
What's `ember update --version` and what's the ember-cli version range in package.json?

**Comment by kellyselden** [comment] 2019-11-02 10:19
Closing for now.

**Closed by kellyselden** 2019-11-02 10:19 UTC

**Comment by robbytx** [comment] 2020-01-18 18:18
I get this error when I use ``--to ~3.12``, or ``3.12.1`` or ``3.12.2``.  It looks like the problem is that https://github.com/ember-cli/ember-new-output/tags doesn't have any of these versions, and it seems like the tool assumes that there is a 1:1 correspondence between ember versions and tags on ember-new-output. 

The workaround was to use ``--to 3.12.0``, which is a supported tag, and then update the ``ember-source`` version in package.json (optional, since npm should automatically select the latest patch version).

**Comment by kellyselden** [comment] 2020-01-18 19:39
ember-cli version is not the same as ember-source version

**Comment by robbytx** [comment] 2020-03-01 07:30
@kellyselden Thanks for the clarification.

Looking at this again, I see that https://www.npmjs.com/package/ember-cli/v/3.12.1 exists so it seems like ``--to 3.12.1`` **should** work.  Any thoughts?

**Comment by kellyselden** [comment] 2020-03-01 09:11
For whatever reason, it was not added to the output repo https://github.com/ember-cli/ember-new-output/tree/v3.12.1. If you run with `--create-custom-diff`, it should work.

**Comment by kellyselden** [comment] 2020-03-02 11:24
Tracking the issue over here https://github.com/ember-cli/ember-cli/issues/9078
