### ISSUE TITLE
ember-cli-update cannot handle paths with spaces

### ISSUE THREAD

**Issue by maxymczech** [ember-cli/ember-cli-update#805] opened 2019-12-06 23:13 UTC
I am on Windows 10, I had an ember app on a path with a space in it, e.g.

```
D:\work\space here\ember-app\
```

`ember-cli-update` couldn't handle this path and failed somewhere mid-process, also messing up my git repository.

**Comment by kellyselden** [comment] 2019-12-08 12:42
Duplicate of #687

**Closed by kellyselden** 2019-12-08 12:42 UTC
